### ISSUE TITLE
README Example Doesn't Work

### ISSUE THREAD

**Issue by dinagraves** [GoogleCloudPlatform/cloud-builders#698] opened 2020-06-17 22:26 UTC
I tried pasting in the example under "[Sharing packages across steps](https://github.com/GoogleCloudPlatform/cloud-builders/tree/master/go#note-2-sharing-packages-across-steps)" and received this error:

```
Starting Step #1
Step #1: Already have image: golang
Step #1: go list -m: module github.com/golang/glog: not a known dependency
Finished Step #1
ERROR
ERROR: build step 1 "golang" failed: step exited with non-zero status: 1
```

My cloudbuild was very simply copy and pasted from the example:

```
- name: golang
  env:
  - GO111MODULE=on
  args: ['go','get','-u','github.com/golang/glog']
  volumes:
  - name: go-modules
    path: /go

- name: golang
  env:
  - GO111MODULE=on
  args: ['go','list','-f','{{ .Dir }}','-m','github.com/golang/glog']
  volumes:
  - name: go-modules
    path: /go
```

**Comment by tbpg** [comment] 2020-06-18 18:56
I was able to reproduce the issue locally. It seems to be fixed by creating a `go.mod`.

```
$ cd $(mktemp -d)
# Create cloudbuild.yaml file.
$ gcloud builds submit
# Get the error above.
$ go mod init example.com/tbpg
$ gcloud builds submit
# Success!
```

I'll send a PR to update the README to say you need to have a `go.mod` file. Alternatively, we could run `go mod init` as a step in the build.

**Comment by bendory** [comment] 2020-06-18 19:00
Thanks @tbpg -- for your PR, please do whichever of those you think will be more intuitive for a new user.

**Closed** 2020-06-18 19:29 UTC
Labels: bug, help wanted
