### ISSUE TITLE
`gke-deploy/kubectl apply` drops all hostAlias entries when removing a duplicate entry from an existing object

### ISSUE THREAD

**Issue by chandanpasunoori** [GoogleCloudPlatform/cloud-builders#690] opened 2020-06-02 19:46 UTC
https://github.com/kubernetes/kubernetes/issues/91670
https://github.com/kubernetes/kubernetes/issues/58477

## Affected builder image

(e.g., `gcr.io/cloud-builders/gke-deploy`)

## Expected Behavior
build should fail if duplicates entries are in deployment.yaml
## Actual Behavior
deleting entries
## Steps to Reproduce the Problem

1. steps and related files are reported in https://github.com/kubernetes/kubernetes/issues/91670

## Additional Info
this is not direct issue but this builder meant for automation and the above problem so serious in automation for production environments.

**Comment by ChrisGe4** [comment] 2020-06-02 23:03
Thanks for reporting this issue. Since the underlying problem is from kubectl, and we expect the bug to be fixed there, rather than in gke-deploy.

**Comment by bendory** [comment] 2020-06-03 00:31
I'm closing this as functionally a duplicate of https://github.com/kubernetes/kubernetes/issues/91670.

**Closed by bendory** 2020-06-03 00:31 UTC
Labels: duplicate
