### ISSUE TITLE
Update gke-deploy 

### ISSUE THREAD

**Issue by mike-ensor** [GoogleCloudPlatform/cloud-builders#711] opened 2020-07-31 21:54 UTC
## Affected builder image

`gcr.io/cloud-builders/gke-deploy`

## Expected Behavior
`kubectl version` is up-to-date (1.16+)

## Actual Behavior
`kubectl version` is 1.13

## Steps to Reproduce the Problem

1. Pull image `docker pull gcr.io/cloud-builders/gke-deploy:stable`
1. Run image `docker run --rm -it --entrypoint /bin/bash gcr.io/cloud-builders/gke-deploy:stable`
1. View version `kubectl version` -- version 1.13

## Additional Info
Looking at the Dockerfile, this should be simple by just running the build again

**Comment by bendory** [comment] 2020-08-03 01:09
@joonlim PTAL

**Comment by joonlim** [comment] 2020-08-03 13:23
Hi @mike-ensor thanks for reporting the issue.

The version of `kubectl` for gke-deploy is tied to the version provided by Google Cloud: https://github.com/GoogleCloudPlatform/cloud-builders/blob/master/gke-deploy/Dockerfile. If the latest version of `kubectl` is needed, we may have to wait for `gcloud` to begin providing a newer version. Another solution may be to build your own `gke-deploy` container and install the latest version of `kubectl` in the container.

Also, it is safe to use the latest version of the `gcr.io/cloud-builders/gke-deploy` container, which today uses `kubectl` with version `v1.14.10`.

**Comment by bendory** [comment] 2020-08-03 13:29
Closing as "works as intended."

**Closed** 2020-08-03 13:28 UTC

**Comment by mike-ensor** [comment] 2020-08-03 17:32
When using `gcloud`, the `kubectl` is 1.16, so this docker image is just out of date.  What I'm asking for is not to add functionality, just run the update of the public image so the dependent projects can use up-to-date functionality.  September 2020 will EOL version 1.14.

@bendory

**Comment by bendory** [comment] 2020-08-03 18:18
@mike-ensor per @joonlim's comments, we are inheriting from the Cloud SDK container which continues (even in the latest version) to default `kubectl` to `1.15`. We follow this versioning in the GCB version for consistency.

Note that `1.16` and `1.17` are also available and can be specified for use via `entrypoint` in our `cloudbuild.yaml` or (per the usage) by setting the `KUBECTL_VERSION` ennvar.

```
$ docker run --rm --entrypoint kubectl      gcr.io/cloud-builders/kubectl version
Client Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-dispatcher", GitCommit:"f2a77f678d6baccda27740d700f6cba2754dfacf", GitTreeState:"clean", BuildDate:"2020-04-21T04:42:07Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
...
$ docker run --rm --entrypoint kubectl.1.16 gcr.io/cloud-builders/kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.9", GitCommit:"a17149e1a189050796ced469dbd78d380f2ed5ef", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:51Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
...
$ docker run --rm --entrypoint kubectl.1.17 gcr.io/cloud-builders/kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.5", GitCommit:"e0fccafd69541e3750d460ba0f9743b90336f24f", GitTreeState:"clean", BuildDate:"2020-04-16T11:44:03Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
...
```
