### ISSUE TITLE
No yarn repositories working

### ISSUE THREAD

**Issue by ollydixon** [GoogleCloudPlatform/cloud-builders#712] opened 2020-08-06 10:16 UTC
All of a sudden with no changes we cannot deploy any of our node projects anymore. One of them needs a critical update.

Using Node 10.

We're seeing errors like so
`error An unexpected error occurred: "https://registry.yarnpkg.com/@protobufjs/base64/-/base64-1.1.2.tgz: Request failed \"404 Not Found\"".`

Not really sure what to do anymore. We tried disabled and enabling the API, using no cache builds, stumped..

Each time we run this we get a different error.

`error An unexpected error occurred: "https://registry.yarnpkg.com/@protobufjs/aspromise/-/aspromise-1.1.2.tgz: Request failed \"404 Not Found\"".`

**Comment by MitchSRobinson** [comment] 2020-08-06 10:45
My team has just run into a similar issue but using the `gcr.io/cloud-builders/npm` build image.

**Comment by ollydixon** [comment] 2020-08-06 10:46
Yeah, we had to temporarily scrap yarn across 31 projects :-D amazing

**Comment by bendory** [comment] 2020-08-06 12:42
This sounds like you are reporting an issue with the hosted Cloud Build service. 

Issues with the hosted service should be reported to your Google Cloud Support team or reported via the public issue tracker at
https://issuetracker.google.com/issues/new?component=190802&template=1162743.

I have created this issue on your behalf:
https://issuetracker.google.com/issues/163024927

Please move this conversation to Google's public issue tracker. Note that the first thing we'll need is a reproducible test case; I tried to put one together based on your report, but my test case worked fine.

I am closing this GitHub issue as off-topic.

@ollydixon @MitchSRobinson

**Closed by bendory** 2020-08-06 12:42 UTC

**Comment by bendory** [comment] 2020-08-06 14:16
Root cause appears to be a `node` repository outage unrelated to any image in this repository and unrelated to the hosted Cloud Build service.

https://status.npmjs.org/incidents/cksjqc1w11v5
