### ISSUE TITLE
[FR] Yarn 2 out-of-the-box compatibility

### ISSUE THREAD

**Issue by sylvainar** [GoogleCloudPlatform/cloud-builders#746] opened 2021-02-05 09:42 UTC
## Notice

**To request a feature in the hosted Google Cloud Build service, please contact your Google Cloud Support representative or suggest your feature using [Google's public issue tracker](https://issuetracker.google.com/issues/new?component=190802&template=1162743).**

This GitHub issue tracker is intended for feature requests in the officially supported builder images __only__. This issue tracker is __not__ the right place to request features like triggers or notifications.

If you're not sure where to suggest your feature, use [Google's public issue tracker](https://issuetracker.google.com/issues/new?component=190802&template=1162743).

## Detailed Feature Information

**Which builder is relevant to this request?**
Node / Yarn

**Is your feature request related to a problem? Please describe.**
Yarn 2 is not currently properly supported by cloud-build:
- Caching is not efficient (every package is fetched at every build)
![Screenshot_20210205_103923](https://user-images.githubusercontent.com/9823286/107016609-6c09b000-679e-11eb-8741-584b3b00d1f1.png)
- There are a lot of warnings, like this one:
```
2021-02-05 10:32:13.866 CET
Step #6 - "builder": ➤ YN0050: The --frozen-lockfile option is deprecated; use --immutable and/or --immutable-cache instead
```
- Install seems to occur twice, without cache, which makes almost all my builds ending up in timeouts
![Screenshot_20210205_104107](https://user-images.githubusercontent.com/9823286/107016804-aa06d400-679e-11eb-8d8d-2c543ff75351.png)

**Describe the solution you'd like**
Out-of-the-box yarn 2 integration.

**Describe alternatives you've considered**
_currently working on a workaround, will add insights with my progress_

**Additional context**
...

**Comment by sylvainar** [comment] 2021-02-05 10:47
Hm, so problem seems to be bigger than that, since GAE doesn't seems to support yarn2 at all

**Comment by bendory** [comment] 2021-02-08 15:19
So IIUC, you are asking that a yarn2-compatible builder be added @sylvainar?

**Comment by sylvainar** [comment] 2021-02-09 21:44
That would be great indeed, however I'm mostly using Cloud Build to deploy on GAE and I'm not totally sure of the compatibility GAE/yarn2 yet, I can't find any documentation on the web. Maybe that's a bit too soon, anyway I ended up roll backing to yarn1 on my side.

**Comment by bendory** [comment] 2021-02-10 16:27
I'm not a `yarn` user, but it [looks to me like it's the same CLI with different options and default settings](https://next.yarnpkg.com/getting-started/migration#step-by-step). Am I misunderstanding?

**Comment by sylvainar** [comment] 2021-02-11 15:26
They do indeed, however it seems that we need extra parameters or configuration linked to the issues I posted in the first post.

**Comment by bendory** [comment] 2021-02-11 15:29
> They do indeed, however it seems that we need extra parameters or configuration linked to the issues I posted in the first post.

Perhaps I'm misunderstanding something (again, I'm not a `yarn` user) -- is there a reason that you can't pass those extra parameters to your build step as args? Is there a reason you can't submit the required configuration as part of your build?

I'm having trouble understanding what the issue is that you are reporting regarding the existing `yarn` build step?

**Comment by sylvainar** [comment] 2021-02-12 14:47
I'm a beginner in Cloud Build, in fact I only learned recently that having a `gcp-build` in your `package.json` while deploying to GAE triggers a Cloud Build job. What I miss is, why does it work so well with yarn1 when it struggles that much with yarn2 ?

I can probably add some parameters to the command but it kinda break the "flawless integration" between GAE and Cloud Build that you have out-of-the-box with yarn1.

**Comment by bendory** [comment] 2021-02-12 15:21
I'm closing this as WAI; there is no reported issue here with our existing `yarn` builder.

Please report App Engine issues using the [App Engine Issue Tracker](https://b.corp.google.com/issues/new?component=187191&template=1162848) or please escalate your individual issue to your Google Cloud Support representative.

**Closed by bendory** 2021-02-12 15:21 UTC
Labels: enhancement, feature request, help wanted
