### ISSUE TITLE
cloudbuild.yaml location conflicts on Cloud Build GitHub App & AppEngine

### ISSUE THREAD

**Issue by pokutuna** [GoogleCloudPlatform/cloud-builders#503] opened 2019-06-20 16:49 UTC
I'm using AppEngine flexible environment (not custom runtime) and [Cloud Build GitHub App](https://github.com/marketplace/google-cloud-build) for testing.

But AppEngine deploy flow and the GitHub App seem not to work together.

> $ gcloud app deploy
> ...
> ERROR: (gcloud.app.deploy) There is a cloudbuild.yaml in the current directory, and the runtime field in /path/to/my/repo/app.yaml is currently set to [runtime: go1.12]. To use your cloudbuild.yaml to build a custom runtime, set the runtime field to [runtime: custom]. To continue using the [go1.12] runtime, please remove the cloudbuild.yaml from this directory.

The Cloud Build GitHub App expects `cloudbuild.yaml` is in repository root directory.

`gcloud app deploy` seems to expect deploying custom runtime when `cloudbuild.yaml` is in repository root.

Is there a way to use them together?

```sh
$ gcloud --version
Google Cloud SDK 251.0.0
alpha 2019.05.17
app-engine-go
app-engine-python 1.9.86
beta 2019.05.17
bq 2.0.43
cloud-datastore-emulator 2.1.0
core 2019.06.14
gsutil 4.38
```

**Comment by ImJasonH** [comment] 2019-06-20 16:59
This sounds like a duplicate of https://github.com/GoogleCloudPlatform/cloud-builders/issues/397 -- the current workaround is to rename `cloudbuild.yaml` to something else, or move it to a subdirectory. I'll ping our internal bug tracking this issue.

**Closed by ImJasonH** 2019-06-20 16:59 UTC
